title: 'National Library Exhibitions'
title-abbreviated: 'National Library Exhibitions'
description: 'Exhibitions organised by National Library Singapore'
url: 'https://exhibitions.nlb.gov.sg/'
google-analytics: UA-50449401-28
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
    - jekyll-feed
    - jekyll-assets
    - jekyll-paginate
    - jekyll-sitemap
resources_name: exhibitions
paginate: 12
paginate_path: '/exhibitons/page:num'
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
exclude:
    - travis-script.js
    - .travis.yml
    - README.md
    - package.json
    - package-lock.json
    - node_modules
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - Gemfile
    - Gemfile.lock
collections:
    exhibitions:
        output: true
    current-exhibitions:
        output: true
    past-exhibitions:
        output: true
    newsgallery:
        output: true
    newsgallery-virtual:
        output: true
    raregallery:
        output: true
    onpaper:
        output: true
    nldonorsgallery:
        output: true
    bookstobytes:
        output: true
    centenary:
        output: true
    thefirstprint:
        output: true
    sellingdreams:
        output: true
    talesofthemalayworld:
        output: true
    shakespearesfirstfolio:
        output: true
    anatomy:
        output: true
    scriptandstage:
        output: true
    fromthestacks:
        output: true
    poetryonplatforms:
        output: true
    geographic:
        output: true
    slpioneers:
        output: true
favicon: /images/cropped-nlb-favicon_192.png
google_analytics: null
permalink: none
baseurl: ""
defaults:
    - scope:
          path: ""
      values:
          layout: page
