title: National Library Exhibitions
title-abbreviated: National Library Exhibitions
description: Exhibitions organised by National Library Singapore
url: https://exhibitions.nlb.gov.sg
google_analytics: UA-50449401-28
google_analytics_ga4: G-9YJW84HPCD
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
paginate: 12
paginate_path: /exhibitons/page:num
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
favicon: /images/nlb_favicon_64.png
permalink: none
baseurl: ""
defaults:
  - scope:
      path: ""
    values:
      layout: page
colors:
  primary-color: "#2D3436"
  secondary-color: "#E21216"
  media-colors:
    - title: media-color-one
      color: "#2d3436"
    - title: media-color-two
      color: "#e21216"
    - title: media-color-three
      color: "#00838f"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#00838f"
staging: https://staging.d2bmwdo27gmnoc.amplifyapp.com/
prod: https://master.d2bmwdo27gmnoc.amplifyapp.com/
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
facebook-pixel: ""
shareicon: /images/isomer-logo.svg
is_government: false
linkedin-insights: ""
